### PR TITLE
Don't crash on vote with no open poll

### LINKED ISSUE #49: "Vote!" button errors without open polls

### PR DESCRIPTION
**Pull request by luukveenis**
Currently if a users clicks the Vote! button when there is no poll open,
the app will crash. This is caused by the `Poll.current.brewery` call when
loading the beers. This fixes that issue and also redirects the user
back to their previous page with a warning message.

This should resolve #49

### CODE REVIEW

File: app/controllers/ballots_controller.rb [hunk 1]
```diff
@@ -47,7 +52,7 @@ def load_ballot
 
   def load_all_beers
     @beers =
-      if brewery = Poll.current.brewery.presence
+      if brewery = Poll.current.try(:brewery)
```
Comment (graygilmore) [inline app/controllers/ballots_controller.rb:55]: I'm interested in why this change is needed. Won't `Poll.current.brewery.presence` just return `nil`?

Comment (Senjai) [inline app/controllers/ballots_controller.rb:55]: Wouldn't Poll.current.brewery return nil? :trollface: Don't need the presence check.

Comment (graygilmore) [inline app/controllers/ballots_controller.rb:55]: Presence returns the string, not a boolean. We're assigning the value to `brewery`.

Aaahhhh, the issue is that there might not be a current poll.

Comment (luukveenis) [inline app/controllers/ballots_controller.rb:55]: Yeah the issue is it crashing when there is no poll. When there's no poll you're calling brewery on nil.
